id: P0F376910
initial_creation_type: input
source_metadata:
  title: Sixteen Arhats
  language: en
  description: 'A selection of texts related to the Sixteen Arhats or Sixteen Elders
    (ṣoḍaśa sthavirāḥ; Tib. gnas brtan bcu drug):'
  volume:
    89351e7a3dda4c779b0aea442c47333e:
      title: A Brief Practice of Paying Homage and Making Offerings to the Sixteen
        Elders
      parent: Practices
    d8d456dbd3fd435bbbfa0ab9e96f23f7:
      title: 'The Heart of Wish-Fulfilling Jewels: A Brief Practice for Paying Homage
        and Making Offerings to the Buddha together with his retinue of Arhats'
      parent: Practices
    b421f0588eff4580b68eb6550559b0d6:
      title: A Practice of Paying Homage and Making Offerings to the Sixteen Elders
      parent: Practices
    a7965eb9e11c44dd9beeb7992a29e4e7:
      title: A Brief Practice for Paying Homage and Making Offerings to the Buddha
        together with his retinue of Arhats
      parent: Practices
    9d9b358d84fd4a92a556a725d114f615:
      title: Supplication to Lord Buddha together with the Sixteen Arhats
      parent: Prayers
created_at: '2022-03-01T05:51:16.713993'
last_modified_at: '2022-03-01T05:51:16.713999'
